export enum StakingStrategies {
    KELLY_CRITERION = 'KELLY_CRITERION',
    FIXED_STAKE = 'FIXED_STAKE',
    FIXED_PERCENTAGE = 'FIXED_PERCENTAGE',
    MARTINGALE_SYSTEM = 'MARTINGALE_SYSTEM',
    ANTI_MARTINGALE_SYSTEM = 'ANTI_MARTINGALE_SYSTEM',
    FIBONACCI_SEQUENCE = 'FIBONACCI_SEQUENCE',
    D_ALEMBERT_SYSTEM = 'D_ALEMBERT_SYSTEM',
    PROPORTIONAL_BETTING = 'PROPORTIONAL_BETTING',
    UNIT_BETTING = 'UNIT_BETTING',
    CONTRA_D_ALEMBERT_SYSTEM = 'CONTRA_D_ALEMBERT_SYSTEM',
    MILLER_STRATEGY = 'MILLER_STRATEGY',
}