export enum StakingStrategies {
    KELLY_CRITERION = 'KELLY CRITERION',
    FIXED_STAKE = 'FIXED STAKE',
    FIXED_PERCENTAGE = 'FIXED PERCENTAGE',
    MARTINGALE = 'MARTINGALE SYSTEM',
    ANTI_MARTINGALE = 'ANTI-MARTINGALE SYSTEM',
    FIBONACCI = 'FIBONACCI SEQUENCE',
    D_ALEMBERT = 'D\'ALEMBERT SYSTEM',
    PROPORTIONAL_BETTING = 'PROPORTIONAL BETTING',
    UNIT_BETTING = 'UNIT BETTING',
    CONTRA_D_ALEMBERT = 'CONTRA D\'ALEMBERT SYSTEM',
    MILLER = 'MILLER STRATEGY',
}