pub const SBS_V1_DB_NAME: &str = "SBSV1";
pub const NBA_GAMES_HISTORICAL_COLLECTION_NAME: &str = "nba_games_historical";
pub const NBA_ODDS_HISTORICAL_COLLECTION_NAME: &str = "nba_odds_historical";
pub const NBA_PLAYER_AGGREGATED_GAME_STATS_HISTORICAL: &str = "NBA_PLAYER_AGGREGATED_GAME_STATS_HISTORICAL";
pub const NBA_TEAM_AGGREGATED_GAME_STATS_HISTORICAL: &str = "NBA_TEAM_AGGREGATED_GAME_STATS_HISTORICAL";