use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct NbaBacktestPlayerFeatures {
    pub date_start: DateTime<Utc>,
    pub team_id: f64,
    pub opponent_team_id: f64,
    pub age: f64,
    
    /* player stats */
    pub points: f64,
    pub min: f64,
    pub fgm: f64,
    pub fga: f64,
    pub fgp: f64,
    pub ftm: f64,
    pub fta: f64,
    pub ftp: f64,
    pub tpm: f64,
    pub tpa: f64,
    pub tpp: f64,
    pub off_reb: f64,
    pub def_reb: f64,
    pub tot_reb: f64,
    pub assists: f64,
    pub p_fouls: f64,
    pub steals: f64,
    pub turnovers: f64,
    pub blocks: f64,
    pub plus_minus: f64,

    /* Expanding Average Fields */
    pub expanding_avg_points: f64,
    pub expanding_avg_min: f64,
    pub expanding_avg_fgm: f64,
    pub expanding_avg_fga: f64,
    pub expanding_avg_fgp: f64,
    pub expanding_avg_ftm: f64,
    pub expanding_avg_fta: f64,
    pub expanding_avg_ftp: f64,
    pub expanding_avg_tpm: f64,
    pub expanding_avg_tpa: f64,
    pub expanding_avg_tpp: f64,
    pub expanding_avg_off_reb: f64,
    pub expanding_avg_def_reb: f64,
    pub expanding_avg_tot_reb: f64,
    pub expanding_avg_assists: f64,
    pub expanding_avg_p_fouls: f64,
    pub expanding_avg_steals: f64,
    pub expanding_avg_turnovers: f64,
    pub expanding_avg_blocks: f64,
    pub expanding_avg_plus_minus: f64,
    
    /* 5-Game Moving Average Fields */
    pub rolling_avg_5_points: f64,
    pub rolling_avg_5_min: f64,
    pub rolling_avg_5_fgm: f64,
    pub rolling_avg_5_fga: f64,
    pub rolling_avg_5_fgp: f64,
    pub rolling_avg_5_ftm: f64,
    pub rolling_avg_5_fta: f64,
    pub rolling_avg_5_ftp: f64,
    pub rolling_avg_5_tpm: f64,
    pub rolling_avg_5_tpa: f64,
    pub rolling_avg_5_tpp: f64,
    pub rolling_avg_5_off_reb: f64,
    pub rolling_avg_5_def_reb: f64,
    pub rolling_avg_5_tot_reb: f64,
    pub rolling_avg_5_assists: f64,
    pub rolling_avg_5_p_fouls: f64,
    pub rolling_avg_5_steals: f64,
    pub rolling_avg_5_turnovers: f64,
    pub rolling_avg_5_blocks: f64,
    pub rolling_avg_5_plus_minus: f64,
    
    /* 10-Game Moving Average Fields */
    pub rolling_avg_10_points: f64,   
    pub rolling_avg_10_min: f64,
    pub rolling_avg_10_fgm: f64,
    pub rolling_avg_10_fga: f64,
    pub rolling_avg_10_fgp: f64,
    pub rolling_avg_10_ftm: f64,
    pub rolling_avg_10_fta: f64,
    pub rolling_avg_10_ftp: f64,
    pub rolling_avg_10_tpm: f64,
    pub rolling_avg_10_tpa: f64,
    pub rolling_avg_10_tpp: f64,
    pub rolling_avg_10_off_reb: f64,
    pub rolling_avg_10_def_reb: f64,
    pub rolling_avg_10_tot_reb: f64,
    pub rolling_avg_10_assists: f64,
    pub rolling_avg_10_p_fouls: f64,
    pub rolling_avg_10_steals: f64,
    pub rolling_avg_10_turnovers: f64,
    pub rolling_avg_10_blocks: f64,
    pub rolling_avg_10_plus_minus: f64,
}