export const NbaTeams = [
    { teamName: 'Atlanta Hawks', teamNickname: 'Hawks' },
    { teamName: 'Boston Celtics', teamNickname: 'Celtics' },
    { teamName: 'Brooklyn Nets', teamNickname: 'Nets' },
    { teamName: 'Charlotte Hornets', teamNickname: 'Hornets' },
    { teamName: 'Chicago Bulls', teamNickname: 'Bulls' },
    { teamName: 'Cleveland Cavaliers', teamNickname: 'Cavaliers' },
    { teamName: 'Dallas Mavericks', teamNickname: 'Mavericks' },
    { teamName: 'Denver Nuggets', teamNickname: 'Nuggets' },
    { teamName: 'Detroit Pistons', teamNickname: 'Pistons' },
    { teamName: 'Golden State Warriors', teamNickname: 'Warriors' },
    { teamName: 'Houston Rockets', teamNickname: 'Rockets' },
    { teamName: 'Indiana Pacers', teamNickname: 'Pacers' },
    { teamName: 'LA Clippers', teamNickname: 'Clippers' },
    { teamName: 'Los Angeles Lakers', teamNickname: 'Lakers' },
    { teamName: 'Memphis Grizzlies', teamNickname: 'Grizzlies' },
    { teamName: 'Miami Heat', teamNickname: 'Heat' },
    { teamName: 'Milwaukee Bucks', teamNickname: 'Bucks'},
    { teamName: 'Minnesota Timberwolves', teamNickname: 'Timberwolves' },
    { teamName: 'New Orleans Pelicans', teamNickname: 'Pelicans' },
    { teamName: 'New York Knicks', teamNickname: 'Knicks' },
    { teamName: 'Oklahoma City Thunder', teamNickname: 'Thunder' },
    { teamName: 'Orlando Magic', teamNickname: 'Magic' },
    { teamName: 'Philadelphia 76ers', teamNickname: '76ers' },
    { teamName: 'Phoenix Suns', teamNickname: 'Suns' },
    { teamName: 'Portland Trail Blazers', teamNickname: 'Trail Blazers' },
    { teamName: 'Sacramento Kings', teamNickname: 'Kings' },
    { teamName: 'San Antonio Spurs', teamNickname: 'Spurs' },
    { teamName: 'Toronto Raptors', teamNickname: 'Raptors' },
    { teamName: 'Utah Jazz', teamNickname: 'Jazz' },
    { teamName: 'Washington Wizards', teamNickname: 'Wizards' }
]